(define (atom? x) (and (not (pair? x)) (not (null? x))))
(define (lat? l)
  (cond ((null? l) #t)
        ((atom? (car l)) (lat? (cdr l)))
        (else #f)))
(define (member? a lat)
  (cond ((null? lat) #f)
        (else (or (eq? a (car lat)))
              (member? a (cdr lat)))))
