(load "stars.scm")
(define (numbered? l)
  (cond ((atom? l) (number? l))
        (else (and (numbered? (car l))
                   (numbered? (caddr l))))))

(define (value nexp)
  (cond ((atom? nexp) nexp)
        ((eq? (operator nexp) '+)
         (add (value (first-sub-exp nexp))
              (value (second-sub-exp nexp))))
        ((eq? (operator nexp) '*)
         (mul (value (first-sub-exp nexp))
              (value (second-sub-exp nexp))))
        (else
         (pow (value (first-sub-exp nexp))
              (value (second-sub-exp nexp))))))

(define (first-sub-exp nexp) (cadr nexp))
(define (second-sub-exp nexp) (caddr nexp))
(define (operator nexp) (car nexp))
